server {
    listen 80;
    server_name hanz.vanila.app brandingproject.hanzmanagement.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name hanz.vanila.app;
    root /var/www/html/public;
    index index.php;

    ssl_certificate /etc/letsencrypt/live/hanz.vanila.app/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hanz.vanila.app/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    client_max_body_size 55M;

    location /storage {
        alias /var/www/html/storage/app/public;
        access_log off;
        expires 7d;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_read_timeout 120;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}

server {
    listen 443 ssl;
    server_name brandingproject.hanzmanagement.com;
    root /var/www/html/public;
    index index.php;

    ssl_certificate /etc/letsencrypt/live/brandingproject.hanzmanagement.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/brandingproject.hanzmanagement.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    client_max_body_size 55M;

    location /storage {
        alias /var/www/html/storage/app/public;
        access_log off;
        expires 7d;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_read_timeout 120;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
